import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Toaster } from 'react-hot-toast';

const Neuropol = localFont({
  src: '../public/fonts/Neuropol.otf',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased`}>
        <Toaster />

        <h1 className={`${Neuropol.className} text-8xl`}>GoPro</h1>
        {children}
      </body>
    </html>
  );
}
